<?php

return [
    'options' => [
        'TECNICAS DE ENSEÑANZA RECURRENTE' => 'TECNICAS DE ENSEÑANZA RECURRENTE',
        'TECNICAS DE ENSEÑANZA AERONAUTICA INICIAL' => 'TECNICAS DE ENSEÑANZA AERONAUTICA INICIAL',
        'PROGRAMA DE INDUCCION TAMEP' => 'PROGRAMA DE INDUCCION TAMEP',
    ],

    'teachers' => [
        'TECNICAS DE ENSEÑANZA RECURRENTE' => 'Ana Rojas',
        'TECNICAS DE ENSEÑANZA AERONAUTICA INICIAL' => 'Jhair Paredes',
        'PROGRAMA DE INDUCCION TAMEP' => 'Carla Mamani',
    ],
];